import '../assets/styles/main.scss';
import type {Metadata} from 'next';
import type {ReactNode} from 'react';
import localFont from 'next/font/local';

const vazirFont = localFont({
  variable: '--font-vazir',
  src: [
    {
      path: '../assets/fonts/Vazirmatn-UI-FD-Thin.woff2',
      weight: '100',
      style: 'normal'
    },
    {
      path: '../assets/fonts/Vazirmatn-UI-FD-ExtraLight.woff2',
      weight: '200',
      style: 'normal'
    },
    {
      path: '../assets/fonts/Vazirmatn-UI-FD-Light.woff2',
      weight: '300',
      style: 'normal'
    },
    {
      path: '../assets/fonts/Vazirmatn-UI-FD-Regular.woff2',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../assets/fonts/Vazirmatn-UI-FD-Medium.woff2',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../assets/fonts/Vazirmatn-UI-FD-SemiBold.woff2',
      weight: '600',
      style: 'normal'
    },
    {
      path: '../assets/fonts/Vazirmatn-UI-FD-Bold.woff2',
      weight: '700',
      style: 'normal'
    },
    {
      path: '../assets/fonts/Vazirmatn-UI-FD-ExtraBold.woff2',
      weight: '800',
      style: 'normal'
    },
    {
      path: '../assets/fonts/Vazirmatn-UI-FD-Black.woff2',
      weight: '900',
      style: 'normal'
    }
  ]
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang="fa" dir="rtl" className={vazirFont.variable}>
      <body>{children}</body>
    </html>
  );
}
